---
title: "Datasets"
---

```{r setup, include = FALSE}
source(here::here("R", "document_setup.R"))

htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```

```{r functions}
source(here("R", "load.R"))
source(here("R", "html.R"))
```

```{r load}
dataset_files <- fs::dir_ls(here("data", "datasets"), glob = "*.csv")

datasets <- get_datasets(dataset_files)
```

```{r dashboard}
tags <- htmltools::tags

tags$div(
    class = "row",
    tags$div(
        class = "col-md-3",
        value_box(nrow(datasets), caption = "Datasets", colour = "success",
                  icon = "database")
    ),
    tags$div(
        class = "col-md-3",
        value_box(length(unique(datasets$study)), caption = "Studies",
                  colour = "danger", icon = "file-alt")
    ),
    tags$div(
        class = "col-md-3",
        value_box(length(unique(datasets$organ)), caption = "Organs",
                         colour = "info", icon = "heart")
    ),
    tags$div(
        class = "col-md-3",
        value_box(scales::comma(sum(datasets$ncells)),
                  caption = "Cells", colour = "warning", icon = "splotch")
    )
)
```

```{r counts, fig.height = 10}
plot_data <- datasets %>%
    group_by(animal, organ) %>%
    summarise(
        Datasets = n(),
        Cells    = sum(ncells),
        .groups  = "drop"
    ) %>%
    mutate(organ = fct_reorder(organ, Cells, sum)) %>%
    pivot_longer(
        c(Datasets, Cells),
        names_to = "Type",
        values_to = "Number"
    )

ggplot(plot_data, aes(x = organ, y = Number, fill = animal)) +
    geom_col(position = position_dodge2(preserve = "single")) +
    scale_y_continuous(labels = scales::label_comma(accuracy = 1)) +
    scale_fill_manual(values = c(human = "#F39C12", mouse = "#3498DB")) +
    coord_flip() +
    facet_wrap(~ Type, scales = "free_x") +
    theme(
        text               = element_text(colour = "#2C3E50"),
        legend.position    = "bottom",
        legend.title       = element_blank(), 
        axis.title         = element_blank(),
        axis.text          = element_text(colour = "#2C3E50"),
        strip.background   = element_rect(fill = "#2C3E50"),
        strip.text         = element_text(colour = "white", size = 16),
        panel.border       = element_rect(fill = NA),
        panel.grid         = element_blank(),
        panel.grid.major.x = element_line(colour = "#2C3E50")
    )
```

Table
-----

```{r table}
tbl <- datasets %>%
    reactable::reactable(
        defaultSorted       = "ncells",
        defaultSortOrder    = "desc",
        defaultColDef       = reactable::colDef(
            class       = "cell",
            headerClass = "header",
            headerStyle = list(fontWeight = 700)
        ),
        defaultColGroup = reactable::colGroup(headerClass = "group-header"),
        compact             = TRUE,
        highlight           = TRUE,
        showSortIcon        = FALSE,
        borderless          = TRUE,
        striped             = TRUE,
        showPageSizeOptions = TRUE,
        searchable          = TRUE,
        class               = "custom-table",
        columns = list(
            id = reactable::colDef(show = FALSE),
            animal = reactable::colDef(
                name       = "Species",
                filterable = TRUE,
                width      = 70
            ),
            organ = reactable::colDef(
                name       = "Organ",
                filterable = TRUE,
                width      = 100
            ),
            subtissue = reactable::colDef(
                name       = "Sub-tissues",
                filterable = TRUE,
                width      = 150
            ),
            ncells = reactable::colDef(
                name       = "Cells",
                width      = 60
            ),
            protocol = reactable::colDef(
                name       = "Protocol",
                filterable = TRUE,
                width      = 110
            ),
            counts = reactable::colDef(
                name       = "Counts",
                width      = 70
            ),
            has_celltypes = reactable::colDef(
                name       = "Has cell types?",
                filterable = TRUE,
                width      = 80
            ),
            study = reactable::colDef(
                name       = "Study",
                width      = 120
            ),
            lab = reactable::colDef(
                name       = "Lab",
                width      = 100
            ),
            year = reactable::colDef(
                name       = "Year",
                width      = 50
            )
        )
    )

htmltools::div(class = "custom-table-container", tbl)
```

